### ISSUE TITLE
Practica expresiones booleanas

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/expresiones-boolenas-equipo-jeanette-arlet-salazar-nicolas#2]
[Practica Expresiones Booleanas .pdf](https://github.com/SistemasTecTlaxiaco/expresiones-boolenas-equipo-jeanette-arlet-salazar-nicolas/files/7724602/Practica.Expresiones.Booleanas.pdf)

**Comment by 7177981** [comment]
calificación: 28
 buen diseño y organización del trabajo, pero faltaron las tablas de verdad

**Comment by josealfredo79** [comment]
Bien hecho y revisado
